name: Testing code

on:
  push:
    branches: [ "main" ]
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'assets/**'
      - 'web/**'
  workflow_dispatch:

# global settings for this yml
env:
  FLUTTER_VERSION: '3.27.0'
  BASE_HREF: '/${{ github.event.repository.name }}'
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN_Wheel_of_fortune }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID_My_Group }}
  RUN_URL: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'

permissions:
  contents: write
  pages: write
  actions: write
  id-token: write

concurrency:
  group: "deploy-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-test-release:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.build.outcome }}
      test_status: ${{ steps.test.outcome }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      
      - name: Build Flutter Web
        id: build
        continue-on-error: true
        run: |
          #temporary cruthc
          echo "" >> pubspec.yaml
          echo "dependency_overrides:" >> pubspec.yaml
          echo "  path: 1.9.0" >> pubspec.yaml
          flutter pub get
          flutter build web --release --base-href "/${{ github.event.repository.name }}/"
      
      - name: Notify Telegram if build failed
        if: steps.build.outcome == 'failure'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
            -d text="[ERROR] *Build Failed!*%0A📦 ${{ github.repository }}%0A🔴 Error during Flutter build%0A🔗 [View the failed run](${{ env.RUN_URL }})" \
            -d parse_mode=Markdown

      - name: Test built site
        id: test
        if: steps.build.outcome == 'success'
        continue-on-error: true
        run: |
          npm install -g serve
          serve -s build/web -l 8080 &
          SERVER_PID=$!
          sleep 5
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)

          if [ "$STATUS" != "200" ]; then
            echo "[ERROR] HTTP $STATUS"
            exit 1
          fi
          if curl -s http://localhost:8080 | grep -qiE "error|exception"; then
            echo "[ERROR] Found Errors"
            exit 1
          fi
          echo "[OK] Test passed"
          kill $SERVER_PID
      - name: Notify Telegram if if test failed
        if: steps.test.outcome == 'failure'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
           -d text="[ERROR] *Test Failed!*%0A${{ github.repository}}%0A⚠️Site build built tests failed%0A🔗 [Viev the failed run](${{ env.RUN_URL }})" \
           -d parse_mode=Markdown 
      
      - name: Upload build artifact
        if: steps.test.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
  test-debug: 
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.build-debug.outcome }}
      test_status: ${{ steps.test-debug.outcome }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Build debug version
        id: build-debug 
        continue-on-error: true
        run: |
          #temporary cruthc
          echo "" >> pubspec.yaml
          echo "dependency_overrides:" >> pubspec.yaml
          echo "  path: 1.9.0" >> pubspec.yaml
          flutter pub get
          flutter build web --profile --base-href "/${{ github.event.repository.name }}/"
      - name: Start dev server
        if: steps.build-debug.outcome == 'success'
        run: |
          npm install -g serve
          serve -s build/web -l 8080 &
          sleep 5 
      - name: Testing on virtual machine
        id: test-vm-debug 
        if: steps.build-debug.outcome == 'success'
        continue-on-error: true
        run: |
          npm install -D @playwright/test
          npx playwright install chromium

          npx playwright test --project=chromium 

      - name: Upload debug build artifact
        if: steps.test-vm-debug.outcome == 'success'
        uses: actions/upload-artifact@v4
        with: 
          name: web/build-debug
          path: build/web 

      - name: Notify Telegram if if test failed
        if: steps.build-debug.outcome == 'failure'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
           -d text="[ERROR] *Test Failed!*%0A${{ github.repository}}%0A⚠️Site build built tests failed%0A🔗 [Viev the failed run](${{ env.RUN_URL }})" \
           -d parse_mode=Markdown 
      - name: Notify telegram if test failed
        if: steps.test-vm-debug.outcome == 'failure'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
           -d text="[ERROR] *Test Failed!*%0A${{ github.repository}}%0A⚠️Playwright tests failed%0A🔗 [Viev the failed run](${{ env.RUN_URL }})" \
           -d parse_mode=Markdown 


  deploy:
    needs: [build-and-test-release, test-debug]
    if: |
        needs.build-and-test-release.outputs.test_status == 'success' &&
        needs.test-debug.outputs.test_status == 'success'
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: web-build
          path: build/web
      
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          force_orphan: true
      
      - name: Notify Telegram on success
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
            -d text="[OK] *Deploy success!*%0A${{ github.repository }}%0Ahttps://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/%0A🔗 [View the workflow run](${{ env.RUN_URL }})" \
            -d parse_mode=Markdown

